export const LOAD_COURSE = 'LOAD_COURSE';
export const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';

export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';